# enable ES6
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true # enable React's JSX

# register plugins
plugins:
  - meteor
  - react

# use the rules of eslint-config-airbnb
# and the recommended rules of eslint-plugin-meteor
extends:
  - airbnb/base
  - plugin:meteor/recommended
  - plugin:react/recommended

# registerenvironments
env:
  meteor: true
  browser: true
  node: true


rules:
  # eslint-plugin-meteor
  meteor/no-session: [0] # allow Session
  meteor/prefer-session-equals: [2] # prefer Session.equals instead
  no-underscore-dangle: [0]
  no-unused-vars: [2, {          # http://eslint.org/docs/rules/no-unused-vars
    vars: "local",
    args: "after-used",
    argsIgnorePattern: "^_",
    varsIgnorePattern: "^React$"
  }]
  no-console: 0
  import/no-unresolved: 0

globals:
  # packages
  faker: false
  SimpleSchema: false
  FlowRouter: false # kadira:flow-router
  React: false
  moment: false # momentjs:moment
  # collections
